dist: xenial
language: python
python:
    - "3.7"
install:
    - pip3 install -r requirements.txt
    - pip3 install -r test-requirements.txt
jobs: 
    include:
    - stage: lint and test
    script: 
        - ./scripts/run-lint.sh
        - ./scripts/run-test.sh