dist: xenial
language: python
python:
    - "3.7"
install:
    - pip3 install -r requirements.txt
jobs: 
    include:
    - stage: lint and test
    script: 
        - run-lint.sh
        - run-test.sh